### ISSUE TITLE
Site rendering strangely for Galaxy S5

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#109]
From Will Slack via Slack: "Looks like the join.tts.gsa.gov site isn't friendly for Galaxy S5"
<img width="290" alt="screen shot 2018-06-21 at 7 46 03 pm" src="https://user-images.githubusercontent.com/13383307/41780900-e2476058-75ea-11e8-8755-df7824acb910.png">

**Comment by ctrimm** [comment]
This is also very similar to how the site looks on a Galaxy S8 using Chrome and the built-in browser as well. Screenshot 1 is Chrome & Screenshot 2 is the Samsung Internet Browser - 

![screenshot_20180703-092914_chrome](https://user-images.githubusercontent.com/1751160/42229419-b36c615e-7ea3-11e8-913f-a5ee219e4d8f.jpg)

![screenshot_20180703-092926_samsung internet](https://user-images.githubusercontent.com/1751160/42229446-bca2f440-7ea3-11e8-9d78-89364006de4f.jpg)

**Comment by maya** [comment]
Fixed in #179. Thanks for reporting it 👍
