### ISSUE TITLE
Background contacting applicants current employers

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#11]
**Issue:** Candidates current employers are being notified by the background/security team that the candidate is currently in process for a new job. This is before the candidate has resigned, given notice, etc!!

We need to understand why this is happening and what can be done about it.

Regardless of the outcome of the discussion with HR, we will need to include some information about this so the candidates understand what is going to happen.

**Comment by rooneywp** [comment]
@keithrwilson test

**Comment by awfrancisco** [comment]
Did you end up having this conversation with HR? Is this still something you'd like to add to the site?

**Comment by JennMoran** [comment]
we did have this discussion with HR and this is no longer an issue and can be closed.
