### ISSUE TITLE
Improve hiring process page

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#116]
Based on feedback from a potential applicant provided by @afeld : "I took a look at the 18F application process and I do admit it looked a bit daunting."

The process is daunting and we may even want it to appear so, though that was not the current intent of the page. We can make some minor changes to the page to reduce the potential anxiety that it may cause in applicants.

- [ ]  Add some kind of thing that provides a simplified view of the process as a way of onboarding the potential applicant
- [ ] Make it clear that not all of the information on the hiring process is required reading or that it's not all required at the same time
- [ ] Add TLDR's to the major sections of the pages or something that does something similar

**Comment by awfrancisco** [comment]
Closed by #171
