### ISSUE TITLE
Print View is Poorly Designed

### ISSUE THREAD

**Issue by ctrimm** [18F/join.tts.gsa.gov#124]
While looking thru the site, I figured it would be easier to print out a couple of the pages so I can take notes. However, the print view is wonky due to the `An official website of the United States government` header. The screenshot below does a better explanation of this issue.

The easiest solution for this would be to include [a @media query for print](https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/) in the `site.scss` file or create a `print.scss`. If I have time today/tomorrow, I may try to tackle this.

<img width="1024" alt="screen shot 2018-07-05 at 11 22 24 am" src="https://user-images.githubusercontent.com/1751160/42338279-81faa3e8-8046-11e8-8788-afba5e0e9afd.png">

**Comment by karareinsel** [comment]
GSA HR has to view a PDF of every TTS job posting but the current print view is broken. The TTS team has a workaround but it takes time. Would like the print view to be fixed so that the TTS talent team can easily print PDFs of every TTS job posting so that they are in compliance with GSA HR.

**Comment by adunkman** [comment]
https://github.com/uswds/uswds/issues/2883

**Comment by karareinsel** [comment]
It looks like the print view issue is a USWDS issue and the team was working on it before the shutdown. From Sara Cope - "We had been working on the print stylesheets in both the new and 1.0 version before furlough." Sara is confirming where things stand now that we're post-shutdown. We may add this to the [Shutdown staffing clearinghouse issue](https://github.com/18F/staffing-and-resources/issues/590) for a dev to work on if they have some extra capacity.

**Comment by saracope** [comment]
Was just looking at this with @greensteph. It looks like in the [uswds-jekyll template](https://github.com/18F/uswds-jekyll/blob/9063de07ce09e308437eefba8f8d45f77ea2a9e2/_includes/styles.html) the style declaration is falling back to screen. Can you try to override this locally with `media=all` or just removing it to test. @adunkman

**Comment by mgwalker** [comment]
This appears to be fixed.
