### ISSUE TITLE
Clarify Selective Service requirement

### ISSUE THREAD

**Issue by fureigh** [18F/join.tts.gsa.gov#126]
The [consulting software engineer](https://join.tts.gsa.gov/join/consulting-software-engineer/) position description currently includes the following as a `Key Requirement`:

> Register with Selective Service, if you are a male born after 12/31/1959.

This line isn't entirely accurate, and it's causing transgender would-be applicants confusion and concern.

From [sss.gov](https://www.sss.gov/Registration-Info/Who-Registration):

> Individuals who are born female and changed their gender to male are not required to register. U.S. citizens or immigrants who are born male and changed their gender to female are still required to register.

Considering that the same page lists other reasons someone might be exempt, I suggest we change our standard line to:
 * Register with Selective Service, if you are a [non-exempt](https://www.sss.gov/Registration-Info/Who-Registration) male born after 12/31/1959.

...link and all. Thoughts?

**Comment by esgoodman** [comment]
I believe Corey Mahoney did a lot of work on clarifying selective service requirements for transgender people while working on USCIS. You might ask her for review.

**Comment by fureigh** [comment]
@esgoodman Thank you! I recalled it having come up before but didn't find phrasing in the repos I searched.

Also, I just realized that the phrasing I suggested doesn't account for the fact that transgender women are required to register.

@coreycaitlin, suggestions? Also posted in a couple of Slack channels.

**Comment by commit-dkp** [comment]
@fureigh I'd decouple as many details as possible, so the only revision needed in the future would be if the requirements link moves.  Something like "Register with Selective Service, if you are required by https://www.sss.gov/Registration-Info/Who-Registration".

**Comment by JennMoran** [comment]
The Key Requirements section is not something we put together, but something HR requires us to have up.  I will take the suggestion above to HR and see what they can do!  Thanks for bringing to our attention.

**Comment by fureigh** [comment]
Thanks, @JennMoran! Feel free to loop me in for further context if need be.

**Comment by rooneywp** [comment]
In #127 I've updated the template and all excepted service job postings (the postings where the requirements section is required) using "Register with Selective Service, if you are required by https://www.sss.gov/Registration-Info/Who-Registration". The Requirements section is only visible on open jobs so the changes won't be visible on Upcoming. 

We'll leave it this way until instructed otherwise.

**Comment by fureigh** [comment]
Thanks, @rooneywp!
