### ISSUE TITLE
Upcoming Statement

### ISSUE THREAD

**Issue by JennMoran** [18F/join.tts.gsa.gov#129]
@rooneywp need to be two upcoming statements.  Need to add one statement where we do not have the line "Applications will be open for submission on...".  We could just remove that statement when creating the job template, but then we would need to remember to re-enter it with all that code.

thoughts?

**Comment by JennMoran** [comment]
looks like the job announcement template needs to be edited. i see that the other upcoming role has something else written in the upcoming statement

**Comment by rooneywp** [comment]
I updated the template with the new intro content that has the logic based on opens. I also updated your new file so it should be working correctly.
