### ISSUE TITLE
Add GSA logo, links to footer

### ISSUE THREAD

**Issue by awfrancisco** [18F/join.tts.gsa.gov#174]
Add the GSA logo, navigation links, links to GSA and other required information to the footer.

**Comment by nickttng** [comment]
@Dahianna @JennMoran 

Initial cut to align the footer design with the new TTS visual refresh and to add relevant info (see screenshots below)

- Change medium gray background to dark gray / black background
- Add GSA | TTS logo
- Add Twitter icon link

Question: Are there any other link(s) or relevant info that we should consider adding to the footer? 

Screenshots. Both desktop and mobile views; Left is current while the right is a localhost preview

![jointts-footer-desktop](https://user-images.githubusercontent.com/6327082/61343904-0305c480-a815-11e9-8019-0614d6f6f9b9.png)

![jointts-footer-mobile](https://user-images.githubusercontent.com/6327082/61343905-039e5b00-a815-11e9-81dc-3a6261d99f84.png)

**Comment by Dahianna** [comment]
Hi! I checked with OSC and this is good to go!

**Comment by nickttng** [comment]
This issue can be closed now. Resolved via #270
