### ISSUE TITLE
Visual design for homepage

### ISSUE THREAD

**Issue by awfrancisco** [18F/join.tts.gsa.gov#176]
The current homepage is a basic 1 column text layout with a video. We would like a new visual design that helps inform visitors about TTS, open positions, and how to take the next step towards applying. We recently completed an artifact analysis of private sector career pages. The visual design could follow the [recommendations from that research](https://docs.google.com/document/d/1URJWH_gXLIKGDOdKAhZqvgJ1wo2p5PunVkze87uPeAI/edit#heading=h.e0cygd468zv). 

The design should use the U.S. Web Design System and maintain the color palette and brand of the current site. The final output would a Sketch file that a front-end designer could then implement.

**Comment by jenniferthibault** [comment]
👋 @awfrancisco , @nickttng is moving full time to Login.gov but can still help out with this and make progress over time in his remaining non-billable time. I don't have permissions in this repo to assign him here, but can you?

**Comment by jenniferthibault** [comment]
And same for #177 — I think these should go hand-in-hand

**Comment by awfrancisco** [comment]
Will do. Thanks!

**Comment by nickttng** [comment]
Design has been implemented in #231. This can be closed.
