### ISSUE TITLE
Visual design for interior pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/join.tts.gsa.gov#177]
The site has 5 interior pages with information about how to apply, TTS offices, and working in the government. The pages are just text and can feel long and overwhelming. 

We would like a new visual design that made the information easier to digest and understand. This could be a different design for each page or a template that could be applied across all pages. The pages have not previously been worked on by a visual designer, so the team is open to all suggestions.  

The design should use the U.S. Web Design System and maintain the color palette and brand of the current site. The final output would a Sketch file that a front-end designer could then implement.

**Comment by nickttng** [comment]
Design has been implemented in #231. This can be closed.
