### ISSUE TITLE
Drug Free Workplace language

### ISSUE THREAD

**Issue by JennMoran** [18F/join.tts.gsa.gov#2]
Need to add language on site about GSA being a drug-free workplace

**Comment by awfrancisco** [comment]
Is this language something we need to copy from somewhere, or can we write it ourselves?

**Comment by awfrancisco** [comment]
Sounds good. Do you know of any existing examples we could work off?

**Comment by JennMoran** [comment]
This is the only guidance HR shared with me before: https://insite.gsa.gov/directives-library/gsa-drugfree-workplace-program-97003-oad-extended?term=drug%20free%20policy
