### ISSUE TITLE
Create visual directions / patterns

### ISSUE THREAD

**Issue by nickttng** [18F/join.tts.gsa.gov#205]
This issue focuses on the potential visual directions / patterns, borrowing from [USWDS v.2](https://v2.designsystem.digital.gov/). 

The tasks here will be:
- [x] Create and share with JoinTTS team the directions
- [x] Select the best direction (or if none, continue to iterate until a direction is selected)
   - [x] Work on more visual applications / mockups to get a better idea
- [x] Discuss any additional issues before proceeding to implementation

**Comment by nickttng** [comment]
@awfrancisco @JennMoran @Dahianna 

First two iterations of the current JoinTTS — These focus on the potential color palettes (See last half of this comment)
1. Deep Blue as the primary base: More deep than the current blue seen on the JoinTTS site/navbar; Still retain the familiarity of the TTS brand
2. Black as the primary base: The black takes another direction away from the current TTS brand (The reason why is explained more below).

Meanwhile, the green palette is added as a secondary. While looking at the US Web Design System and other sites, e.g. 18F, PIF, CoE, etc. I realize that the green isn't used much. So, this is something TTS can make green as its own. Also with green, the word 'Transformation' itself can be associated conceptually as 'changing, evolving, growing, remaking.'

**Deep Blue with Green as secondary:** Retains the familiarity of the current brand, but takes a bit further. However, the issue does not entirely address how to make TTS distinctive when keeping the blue as the primary base color.

**Black with blue + green as secondary:** By having black as the primary base, it acts like a neutral, holding vehicle for all other brands (18F's black/blue combo, PIF's and CoE's blue/green combo, etc). So I think the black can be an anchor holding all these brand color combos. Several notes:

-  The blue palette as secondary is the same as 18F's primary, so there is still familiarity between TTS and 18F while keeping the blue palette more subdued to the black primary base
- The green palette as secondary is what TTS can call as its own to give some distinction

**What's next:** We can continue the conversation on whether one of these directions moves it forward / solves the visual strategy issue in #join-site Slack and/or at the next standup meeting. If one of the directions is chosen, we'll start building out how it'll work with UI components, slide decks, etc.

---
**Black-Base**
<img width="1234" alt="color - black - base" src="https://user-images.githubusercontent.com/6327082/53670652-125aeb80-3c41-11e9-97c8-2d5fc0239d78.png">
**Deep-Blue-Base**
<img width="1234" alt="color - deep blue - base" src="https://user-images.githubusercontent.com/6327082/53670653-125aeb80-3c41-11e9-8241-4af79be889f4.png">

---

**Example of black color application**
<img width="2660" alt="example - black - color application - slide" src="https://user-images.githubusercontent.com/6327082/53670654-125aeb80-3c41-11e9-8a95-dd73fc5f5fea.png">

**Example of deep blue color application**
<img width="2660" alt="example - deep blue - color application - slide" src="https://user-images.githubusercontent.com/6327082/53670655-125aeb80-3c41-11e9-9494-25389a2eed33.png">

**Comment by awfrancisco** [comment]
This is great work. Thanks @nickttng! Dahianna is out Thursday, so I'm going to cancel that meeting and then we can discuss these in our Monday meeting. Does that work for everyone?

**Comment by JennMoran** [comment]
Monday works for me!   thanks!

**Comment by nickttng** [comment]
Thanks. And Monday works for me.

**Comment by nickttng** [comment]
Notes from 3/26 sprint planning: After showing visual mockups of homepage, slides and one-pager, we've decided on black as base with bright blue as secondary, since bright green (secondary) is going beyond the family.

Next: 
- Closing this issue
- Customize the USWDS components for JoinTTS
- Focus on issue #176 - Visual design for homepage
- Focus on issue #177 - Visual design for interior pages
