### ISSUE TITLE
A way to house performance profiles so they are accessible to the public

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#24]
Some way that we can host/house or current version performance profiles so that people can see the types of roles we've hired for in the past or people can use our profiles for their own hiring needs.

Probably just a new page on the join page with a curated selection of profiles and the appropriate contextual information.

**Comment by awfrancisco** [comment]
Is this covered by the upcoming positions section or are you thinking of a larger list of performance profiles? I think this could still be a good addition and would help cultivate a pipeline even if we don't have current job openings.

**Comment by JennMoran** [comment]
This would be a larger list of performance profiles, Not every role we hire for is currently in upcoming

**Comment by awfrancisco** [comment]
Talent decided against this because it would change too often and require too much upkeep. Instead, we'll use the upcoming roles section and the TTS Offices page to help people find the types of roles we hire for.
