### ISSUE TITLE
Menu toggle button does not work on mobile or tablet views

### ISSUE THREAD

**Issue by alexsoble** [18F/join.tts.gsa.gov#294]
## Steps to reproduce:

1. Open the website on a phone, or reduce the width of the browser on desktop until the Menu button appears in the header. 
2. Click the Menu button. 

## Expected behavior: 

Clicking the button should toggle a menu open/closed. 

## Observed behavior: 

A slightly darker overlay appears on the screen, but no menu appears.

**Comment by mgwalker** [comment]
This appears to be fixed.
