### ISSUE TITLE
Example Resume Link broken

### ISSUE THREAD

**Issue by gkenyon** [18F/join.tts.gsa.gov#310]
I was hoping to send in an application for the TTS soon, so I was browsing [the resume section](https://join.tts.gsa.gov/resume/) and got a security error. After a bit of research it looks like the link was a casualty of the domain change and should be changed to ({{site.baseurl}}/resume/) to correctly send people to the example by @amandacostello. I hope this won't be seen as obnoxious, but I figured I would throw a PR in like any other repo. Thanks!

**Comment by mgwalker** [comment]
This seems to have been fixed
