### ISSUE TITLE
A way to describe how to read a federal job announcement

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#33]
Describe what's important about each section
How someone should use each section to help create an application
- Evaluation
- Qualification

**Comment by awfrancisco** [comment]
Drafting content [here](https://docs.google.com/document/d/18fnc7S4UM98KgtV2oYo0vQfge-PVo9RX_YVSApTw5J8/edit#)

**Comment by awfrancisco** [comment]
Closed by #171
